# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from tcp2ros/rtkGPSmessage.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import genpy

class rtkGPSmessage(genpy.Message):
  _md5sum = "579fa07aed9107c31ed915330a747d64"
  _type = "tcp2ros/rtkGPSmessage"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """time ROS_time
string GPS_time
bool vaild_flag
string flash_state
float64 north_meter
float64 east_meter
float64 yaw_rad

"""
  __slots__ = ['ROS_time','GPS_time','vaild_flag','flash_state','north_meter','east_meter','yaw_rad']
  _slot_types = ['time','string','bool','string','float64','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       ROS_time,GPS_time,vaild_flag,flash_state,north_meter,east_meter,yaw_rad

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(rtkGPSmessage, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.ROS_time is None:
        self.ROS_time = genpy.Time()
      if self.GPS_time is None:
        self.GPS_time = ''
      if self.vaild_flag is None:
        self.vaild_flag = False
      if self.flash_state is None:
        self.flash_state = ''
      if self.north_meter is None:
        self.north_meter = 0.
      if self.east_meter is None:
        self.east_meter = 0.
      if self.yaw_rad is None:
        self.yaw_rad = 0.
    else:
      self.ROS_time = genpy.Time()
      self.GPS_time = ''
      self.vaild_flag = False
      self.flash_state = ''
      self.north_meter = 0.
      self.east_meter = 0.
      self.yaw_rad = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_2I().pack(_x.ROS_time.secs, _x.ROS_time.nsecs))
      _x = self.GPS_time
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      buff.write(_get_struct_B().pack(self.vaild_flag))
      _x = self.flash_state
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_3d().pack(_x.north_meter, _x.east_meter, _x.yaw_rad))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.ROS_time is None:
        self.ROS_time = genpy.Time()
      end = 0
      _x = self
      start = end
      end += 8
      (_x.ROS_time.secs, _x.ROS_time.nsecs,) = _get_struct_2I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.GPS_time = str[start:end].decode('utf-8')
      else:
        self.GPS_time = str[start:end]
      start = end
      end += 1
      (self.vaild_flag,) = _get_struct_B().unpack(str[start:end])
      self.vaild_flag = bool(self.vaild_flag)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.flash_state = str[start:end].decode('utf-8')
      else:
        self.flash_state = str[start:end]
      _x = self
      start = end
      end += 24
      (_x.north_meter, _x.east_meter, _x.yaw_rad,) = _get_struct_3d().unpack(str[start:end])
      self.ROS_time.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_2I().pack(_x.ROS_time.secs, _x.ROS_time.nsecs))
      _x = self.GPS_time
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      buff.write(_get_struct_B().pack(self.vaild_flag))
      _x = self.flash_state
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_3d().pack(_x.north_meter, _x.east_meter, _x.yaw_rad))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.ROS_time is None:
        self.ROS_time = genpy.Time()
      end = 0
      _x = self
      start = end
      end += 8
      (_x.ROS_time.secs, _x.ROS_time.nsecs,) = _get_struct_2I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.GPS_time = str[start:end].decode('utf-8')
      else:
        self.GPS_time = str[start:end]
      start = end
      end += 1
      (self.vaild_flag,) = _get_struct_B().unpack(str[start:end])
      self.vaild_flag = bool(self.vaild_flag)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.flash_state = str[start:end].decode('utf-8')
      else:
        self.flash_state = str[start:end]
      _x = self
      start = end
      end += 24
      (_x.north_meter, _x.east_meter, _x.yaw_rad,) = _get_struct_3d().unpack(str[start:end])
      self.ROS_time.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_B = None
def _get_struct_B():
    global _struct_B
    if _struct_B is None:
        _struct_B = struct.Struct("<B")
    return _struct_B
_struct_2I = None
def _get_struct_2I():
    global _struct_2I
    if _struct_2I is None:
        _struct_2I = struct.Struct("<2I")
    return _struct_2I
_struct_3d = None
def _get_struct_3d():
    global _struct_3d
    if _struct_3d is None:
        _struct_3d = struct.Struct("<3d")
    return _struct_3d
