(cl:in-package tcp2ros-msg)
(cl:export '(TIME-VAL
          TIME
          ODOM1-VAL
          ODOM1
          ODOM2-VAL
          ODOM2
          ODOM3-VAL
          ODOM3
          ODOM4-VAL
          ODOM4
          MODE-VAL
          MODE
          TANK_ID-VAL
          TANK_ID
          TRACK_POINT_ID-VAL
          TRACK_POINT_ID
          FIRST_ALIGNMENT-VAL
          FIRST_ALIGNMENT
          LASER_ALIGNMENT-VAL
          LASER_ALIGNMENT
          DISTANCE_ALIGNMENT-VAL
          DISTANCE_ALIGNMENT
          PILLAR_DISTANCE-VAL
          PILLAR_DISTANCE
          PAUSE-VAL
          PAUSE
          STOP-VAL
          STOP
          BACK_HOME-VAL
          BACK_HOME
          OTHER_CAR_X-VAL
          OTHER_CAR_X
          OTHER_CAR_Y-VAL
          OTHER_CAR_Y
          OTHER_CAR_THETA-VAL
          OTHER_CAR_THETA
          INFRARED_RIGHT-VAL
          INFRARED_RIGHT
          INFRARED_LEFT-VAL
          INFRARED_LEFT
          IS_START_CAMERA-VAL
          IS_START_CAMERA
          NEXT_TARGET_NUM-VAL
          NEXT_TARGET_NUM
          CONTROL1-VAL
          CONTROL1
          CONTROL2-VAL
          CONTROL2
          CONTROL3-VAL
          CONTROL3
          CONTROL4-VAL
          CONTROL4
))